"""
data/exp2/cad/ に CAD ファイルを整備する。

- glass_plate.obj : data/glassboard_cad/ からコピー (148×148×2.5mm)
- resin_sheet.obj : 70×100×0.1mm を新規生成
- resin_sheet_fp.obj : FoundationPose 用。厚み 1mm に設定 (0.1mm は ICP 収束に不安定)

使い方:
  python scripts/exp2/setup_cad.py
"""
import shutil
from pathlib import Path

PROJ = Path(__file__).resolve().parent.parent.parent
OUT = PROJ / "data/exp2/cad"
OUT.mkdir(parents=True, exist_ok=True)


def box_obj(x_m: float, y_m: float, z_m: float) -> str:
    """軸対称ボックスの OBJ 文字列。trimesh と同じ頂点順。"""
    hx, hy, hz = x_m / 2, y_m / 2, z_m / 2
    verts = [
        (-hx, -hy, -hz),
        (-hx, -hy,  hz),
        (-hx,  hy, -hz),
        (-hx,  hy,  hz),
        ( hx, -hy, -hz),
        ( hx, -hy,  hz),
        ( hx,  hy, -hz),
        ( hx,  hy,  hz),
    ]
    lines = ["# generated by setup_cad.py"]
    for v in verts:
        lines.append(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}")
    # 12 triangles (same winding as glass_plate.obj)
    faces = [
        (2,4,1),(5,2,1),(1,4,3),(3,5,1),
        (2,8,4),(6,2,5),(6,8,2),(4,8,3),
        (7,5,3),(3,8,7),(7,6,5),(8,6,7),
    ]
    for f in faces:
        lines.append(f"f {f[0]} {f[1]} {f[2]}")
    return "\n".join(lines) + "\n"


def main():
    # ── glass_plate.obj をコピー ──
    src = PROJ / "data/glassboard_cad/glass_plate.obj"
    dst = OUT / "glass_plate.obj"
    shutil.copy2(src, dst)
    print(f"[OK] glass_plate.obj  copied  → {dst}")

    # ── resin_sheet.obj  70×100×0.1mm ──
    obj = box_obj(x_m=0.070, y_m=0.100, z_m=0.001)
    (OUT / "resin_sheet.obj").write_text(obj)
    print(f"[OK] resin_sheet.obj  70×100×0.1mm → {OUT / 'resin_sheet.obj'}")

    # ── resin_sheet_fp.obj  70×100×1mm (FP 用) ──
    obj_fp = box_obj(x_m=0.070, y_m=0.100, z_m=0.010)
    (OUT / "resin_sheet_fp.obj").write_text(obj_fp)
    print(f"[OK] resin_sheet_fp.obj  70×100×1mm (FP用) → {OUT / 'resin_sheet_fp.obj'}")

    print("\ndata/exp2/cad/ の内容:")
    for f in sorted(OUT.iterdir()):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
